### ISSUE TITLE
PHP error, can't log in

### ISSUE THREAD

**Issue by eaglefsd** [HaschekSolutions/0xf.at#2]
Hi,

I can't login anymore. There is also an error shown at the bottom of the page:

```
Warning: Unknown: open(/var/lib/php5/sess_oah67cafqs8df6gebtarje0ru4, O_RDWR) failed: Read-only file system (30) in Unknown on line 0

Warning: Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php5) in Unknown on line 0
```

**Comment by geek-at** [comment]
Thanks! Sadly it's because of [this](https://social.technet.microsoft.com/Forums/office/en-US/e21c5f80-80ff-46be-b2da-76be77642596/ubuntu-guests-to-readonly-filesystem-while-running-backup?forum=linuxintegrationservices)

Works again now (after a restart)

**Comment by eaglefsd** [comment]
Appeared again.
